rem use github gitignore templates via API
rem https://github.com/sloria/gig

rem INSTALL
rem pip install -U gig 

rem API URLS 
rem API_URL = "https://api.github.com/gitignore/templates"
rem GLOBAL_URL = "https://api.github.com/repos/github/gitignore/contents/Global/"
rem TEMPLATE_URL = "https://raw.github.com/github/gitignore/master"
rem HEADER = "########## Generated by gig ###########\n"

rem USAGE
rem gig list
rem gig list --global
rem gig Python Ruby > .gitignore
rem gig C C++ CMake Java VisualStudio

@echo off

set API_URL=https://www.toptal.com/developers/gitignore/api/c,csharp,vs,visualstudio,visualstudiocode,java,maven,c++,cmake,eclipse,netbeans
set OUTPUT_FILE=.gitignore

REM Set the running folder to the current working folder
cd /d "%~dp0"

rem NOTE: this is a ONE-TIME bootstrap script for starting a brand new repo
rem from nothing (see README.md "Repository Setup"). Running it again on this
rem template overwrites .gitignore's project-specific additions (target/,
rem release/, report_*_hist/, README badge exceptions) with the generic
rem toptal.com template - do not run it here; it is documented for reference
rem only.

where curl >nul 2>&1
if errorlevel 1 (
    echo [ERROR] curl not found on PATH. Fix: choco install curl -y
    exit /b 1
)

REM Download the API results using curl
curl -sf -o %OUTPUT_FILE% %API_URL%
if errorlevel 1 (
    echo [ERROR] Could not download %API_URL% - check your network connection.
    exit /b 1
)

echo Downloaded .gitignore file from %API_URL% and saved as %OUTPUT_FILE%

REM Append '**/desktop.ini' to .gitignore
echo **/desktop.ini >> %OUTPUT_FILE%

echo Appended '**/desktop.ini' to %OUTPUT_FILE%
echo Remember to re-add this template's project-specific .gitignore entries
echo (see docs/guide/use-template.en.md) after regenerating from the API.

if not defined CI pause

