#!/bin/sh

echo ":::: DELETE desktop.ini FILES FROM PROJECT AND .GIT FOLDERS ::::"

# Save the current directory
currentDir=$(pwd)

# Change to the root directory of the Git repository
cd "$(git rev-parse --show-toplevel)"

# Deleting desktop.ini files from the project directory and removing them from the Git index
find . -name 'desktop.ini' -type f | while IFS= read -r file; do
    git rm --cached --force --quiet "$file" 2>/dev/null
    rm -f "$file"
done

# Return to the original directory
cd "$currentDir"

echo ":::: DELETE OPERATION COMPLETED ::::"

exit 0
