#!/usr/bin/env python3
"""Link checker for the built MkDocs site (standard library only).

Usage: python scripts/check-links.py site [--verbose]

* Pages generated by the site generator itself ("our own pages") are checked strictly: every relative
  href/src (a, link, script, img, iframe, source) must resolve to a file or a folder with an index.html.
  Any miss makes the exit code 1.
* Standalone third-party HTML (reports/<platform>/<kind>-<tool>/html/ and native/) is only sampled for its entry
  file - those tools (Doxygen, Javadoc, JaCoCo, Maven site, ...) own their own link structure; misses inside them
  are printed as warnings and never fail the run.
* External links (http, https, mailto, tel, data, javascript, #anchor) are ignored.
"""
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

ATTRS = {"a": "href", "link": "href", "script": "src", "img": "src", "iframe": "src", "source": "src"}


class Collect(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        k = ATTRS.get(tag)
        if k and a.get(k):
            if tag == "link" and a.get("rel") in ("preconnect", "dns-prefetch"):
                return
            self.links.append(a[k])


def is_external_area(rel):
    parts = rel.parts
    if parts and parts[0] == "native":
        return True
    return len(parts) >= 4 and parts[0] == "reports" and "html" in parts[3:4]


def resolve(site, page, link):
    u = urlsplit(link)
    if u.scheme or link.startswith(("#", "//", "mailto:", "tel:", "data:", "javascript:")):
        return None
    path = unquote(u.path)
    if not path:
        return None
    base = site if path.startswith("/") else page.parent
    target = (base / path.lstrip("/")).resolve() if path.startswith("/") else (page.parent / path).resolve()
    try:
        target.relative_to(site.resolve())
    except ValueError:
        return False
    if target.is_file():
        return True
    if target.is_dir() and (target / "index.html").is_file():
        return True
    return False


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    verbose = "--verbose" in sys.argv
    if not args:
        sys.exit(__doc__)
    site = Path(args[0]).resolve()
    if not site.is_dir():
        sys.exit("[ERROR] not a folder: %s" % site)
    hard, soft, checked = [], [], 0
    for page in sorted(site.rglob("*.html")):
        rel = page.relative_to(site)
        if rel.as_posix() == "404.html":
            continue  # uses root-relative URLs for the hosting sub-path; only meaningful on the server
        strict = not is_external_area(rel)
        if not strict and page.name != "index.html" and not verbose:
            continue  # sample only entry pages of third-party areas
        c = Collect()
        try:
            c.feed(page.read_text(encoding="utf-8", errors="replace"))
        except Exception as e:  # noqa
            soft.append("%s: cannot parse (%s)" % (rel, e))
            continue
        for link in c.links:
            ok = resolve(site, page, link)
            checked += 1
            if ok is False:
                (hard if strict else soft).append("%s -> %s" % (rel.as_posix(), link))
    print("check-links: %d links checked in %s" % (checked, site))
    for s in soft[:25]:
        print("  [warn] (third-party area) " + s)
    if len(soft) > 25:
        print("  ... %d more warnings" % (len(soft) - 25))
    for h in hard:
        print("  [BROKEN] " + h)
    if hard:
        print("check-links: %d broken link(s) in our own pages" % len(hard))
        sys.exit(1)
    print("check-links: OK (no broken links in our own pages; %d warning(s) in third-party areas)" % len(soft))


if __name__ == "__main__":
    main()
