name: Maven Java Release with Test Coverage Control

on:
  push:
    #branches:
    #  - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check and Generate Release
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
    steps:
      - name: Checkout Source Code from Github
        uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

    steps:
    - name: Setup Java
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash
                
      - name: Perform Maven clean, test, site generation, and packaging
        run: mvn clean test site package
        working-directory: ./calculator-app
                
      - name: Check Test Coverage
        run: |
          # Parse the JaCoCo XML report and check coverage percentage
          covered=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@covered)" coveragereport/jacoco.xml)
          missed=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@missed)" coveragereport/jacoco.xml)
          total=$((covered + missed))
          coverage_percentage=$(awk "BEGIN { print ($covered / $total) * 100 }")
          # Check if coverage is 100%
          if (( $(echo "$coverage_percentage == 100" | bc -l) )); then
            echo "Test coverage is 100%!"
          else
            echo "Test coverage is not 100%."
            exit 1  # Fail the GitHub Actions workflow
          fi
          echo "Coverage Percentage: $coverage_percentage"
          echo "Covered: $covered"
          echo "Missed: $missed"
        working-directory: ./calculator-app

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: Generate Doxygen HTML and XML Documentation
        run: doxygen Doxyfile
        shell: bash

      - name: Generate ReportGenerator HTML Report
        run: reportgenerator "-reports:target/site/jacoco/jacoco.xml" "-sourcedirs:src/main/java" "-targetdir:target/site/coveragereport" -reporttypes:Html
        working-directory: ./calculator-app

      - name: Run Coverxygen
        run: python -m coverxygen --xml-dir ./calculator-app/target/site/doxygen/xml --src-dir ./ --format lcov --output ./calculator-app/target/site/coverxygen/lcov.info --prefix %currentDir%\calculator-app\
        
      - name: Run lcov genhtml
        run: perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\genhtml ./calculator-app\target\site\coverxygen\lcov.info -o calculator-app/target/site/coverxygen
        
      #- name: Archive Coverage Report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: coverage-report
      #    path: coveragereport
          
      - name: Get Commit Summary
        id: commit_summary
        run: echo "::set-output name=summary::$(git log --format=%B -n 10 ${{ github.sha }})"

      - name: Create Release
        id: create_common_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.commit_summary.outputs.summary }}
            
            Asst. Prof. Dr. Ugur CORUH
          draft: false
          prerelease: false
                
      - name: Compress Test Coverage Report
        run: tar -czvf test-coverage-report.tar.gz -C calculator-app/target/site/coveragereport .
        
      - name: Compress Doc Coverage Report
        run: tar -czvf doc-coverage-report.tar.gz -C calculator-app/target/site/coverxygen .

      - name: Compress Doxygen Documentation
        run: tar -czvf app-documents.tar.gz -C calculator-app/target/site/doxygen .
                
      - name: Compress Web Site
        run: tar -czvf app-website.tar.gz -C target/site .
        working-directory: ./calculator-app
        
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./target/calculator-app-1.0-SNAPSHOT.jar
          asset_name: calculator.jar
          asset_content_type: application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          
      - name: Upload Test Coverage Report
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./test-coverage-report.tar.gz
          asset_name: test-coverage-report.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          
      - name: Upload Doc Coverage Report
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./doc-coverage-report.tar.gz
          asset_name: doc-coverage-report.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          
      - name: Upload Doxygen Documentation
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./app-documents.tar.gz
          asset_name: app-documents.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          
      - name: Upload Web Site
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_common_release.outputs.upload_url }}
          asset_path: ./app-website.tar.gz
          asset_name: app-website.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          
      - name: Deploy Web Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MAVEN_TEMPLATE_TOKEN }}
          publish_dir: ./calculator-app/target/site